name = "build-studio"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "build-studio-prod"

[[d1_databases]]
binding = "DB"
database_name = "build-studio-db"
database_id = "your-d1-database-id"

[[kv_namespaces]]
binding = "USERS"
id = "your-kv-namespace-id"

[env.development]
name = "build-studio-dev"

[[d1_databases]]
binding = "DB"
database_name = "build-studio-dev-db"
database_id = "your-dev-d1-database-id"

[[kv_namespaces]]
binding = "USERS"
id = "your-dev-kv-namespace-id"